"""add pay_tribute url

Revision ID: 0d7d3bbd0db6
Revises: 505f0104ac3c
Create Date: 2026-05-15 10:45:11.538918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7d3bbd0db6'
down_revision: Union[str, Sequence[str], None] = '505f0104ac3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('pay_tribute_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'pay_tribute_url')
    # ### end Alembic commands ###
