"""Add prod_id for tribute and yookassa payments

Revision ID: 286fd5743bb4
Revises: e73e7c668b95
Create Date: 2026-05-18 20:18:58.136075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286fd5743bb4'
down_revision: Union[str, Sequence[str], None] = 'e73e7c668b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tribute_payment', schema=None) as batch_op:
        batch_op.alter_column('telegram_user_id',
                              existing_type=sa.BIGINT(),
                              nullable=True)
        batch_op.alter_column('prod_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.create_foreign_key('fk_tribute_payment_prod_id', 'product', [
            'prod_id'], ['id'], ondelete='SET NULL'
        )
    with op.batch_alter_table('yookassa_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'prod_id', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
                              existing_type=sa.BIGINT(),
                              nullable=True)
        batch_op.create_foreign_key('fk_yookassa_payment_prod_id', 'product', [
            'prod_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yookassa_payment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_yookassa_payment_prod_id',
                                 type_='foreignkey')
        batch_op.alter_column('user_id',
                              existing_type=sa.BIGINT(),
                              nullable=False)
        batch_op.drop_column('prod_id')
    with op.batch_alter_table('tribute_payment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tribute_payment_prod_id',
                                 type_='foreignkey')
        batch_op.alter_column('prod_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.alter_column('telegram_user_id',
                              existing_type=sa.BIGINT(),
                              nullable=False)
    # ### end Alembic commands ###
