"""product_name unique

Revision ID: 505f0104ac3c
Revises: 84a6fbca3b0b
Create Date: 2026-05-14 19:16:30.872498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '505f0104ac3c'
down_revision: Union[str, Sequence[str], None] = '84a6fbca3b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint(
            'uq_product_products_name',  ['products_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('uq_product_products_name', type_='unique')
    # ### end Alembic commands ###
