"""add price currency to action table

Revision ID: 81469fd630bb
Revises: fef8a8948d9c
Create Date: 2026-04-29 16:45:25.331914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81469fd630bb'
down_revision: Union[str, Sequence[str], None] = 'fef8a8948d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('action', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action', 'currency')
    op.drop_column('action', 'price')
    # ### end Alembic commands ###
