"""add yookassa_total_amount to product

Revision ID: 84a6fbca3b0b
Revises: b72baa7e5796
Create Date: 2026-05-14 19:01:32.254529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a6fbca3b0b'
down_revision: Union[str, Sequence[str], None] = 'b72baa7e5796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('yookassa_total_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'yookassa_total_amount')
    # ### end Alembic commands ###
