"""Action add product_id create Product Notification tables


Revision ID: b72baa7e5796
Revises: a320400659e8
Create Date: 2026-05-14 16:00:28.002451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72baa7e5796'
down_revision: Union[str, Sequence[str], None] = 'a320400659e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('products_name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('url', sa.String(), nullable=False),
                    sa.Column('free', sa.Boolean(),
                              server_default='true', nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('notification',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('day_delta', sa.Integer(), nullable=False),
                    sa.Column('notification', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['product_id'], ['product.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'product_id',
                sa.Integer(),
                nullable=True
            )
        )
        batch_op.create_foreign_key(
            'fk_action_product_id',  # Имя ключа (обязательно для batch)
            'product',              # Целевая таблица
            ['product_id'],         # Колонка в текущей таблице
            ['id'],                 # Колонка в целевой таблице
            ondelete='SET NULL'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_constraint('fk_action_product_id', type_='foreignkey')
        batch_op.drop_column('product_id')
