"""add emoji for product

Revision ID: e73e7c668b95
Revises: d5b0bc5749c2
Create Date: 2026-05-18 17:20:56.836606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e73e7c668b95'
down_revision: Union[str, Sequence[str], None] = 'd5b0bc5749c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('emojis', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'emojis')
    # ### end Alembic commands ###
